In [ ]:
#NUMPY INTRO

In [1]:
import numpy as np
a=np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
a=np.array([0,1,2,3,4])
print(a)

[0 1 2 3 4]


In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [7]:
len(a)

5

In [9]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a.ndim

2

In [11]:
a.shape

(2, 3)

In [12]:
len(a)

2

In [15]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
a.ndim

3

In [17]:
a.shape

(2, 2, 2)

In [20]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
a=np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [23]:
a=np.linspace(0,2,6)
print(a)

[0.  0.4 0.8 1.2 1.6 2. ]


In [25]:
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [26]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
a=np.eye(3,3,2)
print(a)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [43]:
np.diag(a)

array([1, 2, 3, 4])

In [9]:
import numpy as np
a=np.random.rand(4)
a

array([0.8886155 , 0.40019907, 0.21597563, 0.87567782])

In [11]:
a=np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [12]:
a=np.arange(10,dtype='float32')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [15]:
a=np.zeros((2,2))
print(a)
a.dtype

[[0. 0.]
 [0. 0.]]


dtype('float64')

In [26]:
a=np.arrray([2+3j, 4+4j])
print(a.dtype)

AttributeError: module 'numpy' has no attribute 'arrray'

In [21]:
a=np.array([True,False,True,False])
print(a.dtype)

bool


In [31]:
a=np.arange(10)
print(a)
a[6]

[0 1 2 3 4 5 6 7 8 9]


6

In [33]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [35]:
a[2,2]

3

In [38]:
a=np.diag([1,2,3])
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [40]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[1:7:2]

array([1, 3, 5])

In [47]:
a=np.arange(10)
a[5:6]=8
print(a)

[0 1 2 3 4 8 6 7 8 9]


In [50]:
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [52]:
a=np.arange(10)
b=a[::2]

In [53]:
b

array([0, 2, 4, 6, 8])

In [55]:
b[0]=10

In [56]:
b

array([10,  2,  4,  6,  8])

In [60]:
a=np.arange(10)
c=a[0:5:2]
c

array([0, 2, 4])

In [63]:
a=np.random.randint(1,20,15)
print(a)

[ 2  1  4  9 10  4 18  2  7 10 18 18 11  7  1]


In [65]:
a=np.arange(0,100,10)
a[[2,3,4,4,3,2]]

array([20, 30, 40, 40, 30, 20])

In [69]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [1]:
import numpy as np
a=np.array([1,2,3,4])
a=a+1
print(a)

[2 3 4 5]


In [2]:
a**2

array([ 4,  9, 16, 25], dtype=int32)

In [7]:
a

array([2, 3, 4, 5])

In [8]:
b=np.ones(4)+1
print(b)

[2. 2. 2. 2.]


In [9]:
a-b

array([0., 1., 2., 3.])

In [10]:
a*b

array([ 4.,  6.,  8., 10.])

In [13]:
a=np.diag([1,2,3,4])
a.dot(a)
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [14]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a==b

array([False, False, False, False])

In [16]:
a>b

array([False, False, False, False])

In [17]:
a<b

array([ True,  True,  True,  True])

In [19]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])

In [20]:
np.array_equal(a,b)

False

In [22]:
np.array_equal(a,c)

True

In [23]:
a=np.array([1,0,1,1])
b=np.array([0,0,1,0])
np.logical_or(a,b)

array([ True, False,  True,  True])

In [24]:
np.logical_and(a,b)

array([False, False,  True, False])

In [26]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
a=np.arange(4)
a+np.array([1,2,3,4])

array([1, 3, 5, 7])

In [32]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [38]:
y=np.array([[1,1],[2,2]])
y.sum(axis=0)

array([3, 3])

In [43]:
y.sum(axis=1)

array([2, 4])

In [44]:
a=np.array([1,2,3,4])
np.min(a)

1

In [45]:
np.max(a)

4

In [46]:
np.argmin(a)

0

In [47]:
np.argmax(a)

3

In [48]:
np.all([True,False,True])

False

In [50]:
np.any([True,False,True])

True

In [52]:
x=np.array([1,2,3,4])
np.mean(x)

2.5

In [57]:
x=np.array([[1,2,3,4],[3,4,7,8]])
x.mean()

4.0

In [9]:
import numpy as np
data=np.loadtxt('D:/dataset_1.txt')
data

array([[1.9940e+03, 1.2300e+02, 1.2345e+04],
       [1.9930e+03, 3.2100e+02, 2.1345e+04],
       [1.9900e+03, 8.7600e+02, 8.7654e+04],
       [1.9930e+03, 5.4600e+02, 7.6543e+04],
       [1.9980e+03, 4.5600e+02, 6.9798e+06]])

In [10]:
population=data[:,0:]
print(population)

[[1.9940e+03 1.2300e+02 1.2345e+04]
 [1.9930e+03 3.2100e+02 2.1345e+04]
 [1.9900e+03 8.7600e+02 8.7654e+04]
 [1.9930e+03 5.4600e+02 7.6543e+04]
 [1.9980e+03 4.5600e+02 6.9798e+06]]


In [11]:
np.argmax(population,axis=1)

array([2, 2, 2, 2, 2], dtype=int64)

In [12]:
a=np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [13]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [17]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [21]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b[0,1]=100
b

array([[  1, 100,   3],
       [  4,   5,   6]])

In [30]:
a=np.zeros((2,3))
b=a.T
b.reshape(3,2)
b[0,0]=50
b

array([[50.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [34]:
a=np.arange(4)
a.resize(8,)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [41]:
a=np.array([[2,3,1],[6,4,5]])
b=np.sort(a)
b

array([[1, 2, 3],
       [4, 5, 6]])