In [43]:
import pandas as pd
import numpy as np

In [44]:
data=np.random.randint(0,1000,(100,5))

In [45]:
r1=data[22]
r2=data[33]
r3=data[66]

In [46]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [47]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [48]:
distance_matrix.argmin(axis=1)

array([0, 1, 2, 1, 0, 2, 2, 2, 2, 2, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 2, 1,
       0, 1, 0, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 0, 0, 0, 1,
       1, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 2, 0,
       2, 1, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2, 2, 0, 0, 2, 2, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 2], dtype=int64)

In [49]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [61]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([588.70967742, 525.80645161, 773.83870968, 550.4516129 ,
        424.83870968]),
 array([791.20588235, 506.52941176, 363.64705882, 394.88235294,
        456.14705882]),
 array([293.14285714, 530.2       , 505.82857143, 403.94285714,
        619.85714286]))

In [56]:
len(c1),len(c2),len(c3)

(31, 34, 35)

In [62]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [63]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [64]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [65]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [66]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([582.6       , 604.65714286, 802.        , 574.62857143,
        438.42857143]),
 array([777.84848485, 509.84848485, 336.96969697, 409.27272727,
        472.15151515]),
 array([292.21875, 440.34375, 464.59375, 344.0625 , 607.75   ]))

In [67]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [68]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [69]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [70]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [71]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([591.48717949, 619.64102564, 789.43589744, 576.82051282,
        459.25641026]),
 array([764.2       , 499.53333333, 304.4       , 411.03333333,
        450.26666667]),
 array([303.77419355, 417.        , 456.03225806, 316.16129032,
        611.4516129 ]))

In [72]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [73]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [74]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [75]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [76]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([605.02564103, 638.61538462, 783.05128205, 576.56410256,
        476.87179487]),
 array([748.43333333, 496.63333333, 287.76666667, 425.63333333,
        448.4       ]),
 array([302.        , 395.93548387, 480.16129032, 302.35483871,
        591.09677419]))

In [77]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [78]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [79]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [80]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [81]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([608.36842105, 655.26315789, 778.34210526, 587.07894737,
        492.10526316]),
 array([748.43333333, 496.63333333, 287.76666667, 425.63333333,
        448.4       ]),
 array([307.5    , 383.75   , 495.21875, 298.4375 , 569.4375 ]))

In [82]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [83]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [84]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [85]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [86]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([610.40540541, 669.24324324, 772.45945946, 597.16216216,
        495.75675676]),
 array([748.43333333, 496.63333333, 287.76666667, 425.63333333,
        448.4       ]),
 array([314.33333333, 376.3030303 , 510.39393939, 295.87878788,
        563.        ]))

In [87]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [88]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [89]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [90]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [91]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([609.78947368, 677.84210526, 757.02631579, 607.44736842,
        496.94736842]),
 array([754.        , 479.4137931 , 291.27586207, 406.24137931,
        445.20689655]),
 array([314.33333333, 376.3030303 , 510.39393939, 295.87878788,
        563.        ]))

In [92]:
r1=c1.mean(axis=0)
r2=c2.mean(axis=0)
r3=c3.mean(axis=0)

In [93]:
d1=np.sqrt(((data-r1)*(data-r1)).sum(axis=1))
d2=np.sqrt(((data-r2)*(data-r2)).sum(axis=1))
d3=np.sqrt(((data-r3)*(data-r3)).sum(axis=1))

In [94]:
distance_matrix=np.array(list(zip(d1,d2,d3)))

In [95]:
c1=data[distance_matrix.argmin(axis=1)==0]
c2=data[distance_matrix.argmin(axis=1)==1]
c3=data[distance_matrix.argmin(axis=1)==2]

In [96]:
c1.mean(axis=0),c2.mean(axis=0),c3.mean(axis=0)

(array([621.26315789, 687.31578947, 747.39473684, 620.52631579,
        487.92105263]),
 array([745.96428571, 464.03571429, 287.96428571, 391.57142857,
        443.85714286]),
 array([321.05882353, 381.41176471, 517.44117647, 296.58823529,
        570.73529412]))