In [10]:
x=[1,2,3,4]
y=[7,8]
x.append(y)
x

[1, 2, 3, 4, [7, 8]]

In [14]:
c=[1,2,3,[5,6],[7,8]]
d=[10,11]
c.append(d)
c

[1, 2, 3, [5, 6], [7, 8], [10, 11]]

In [6]:
a=[1,2,3,4]
b=[5,6]
a.extend(b)
a

[1, 2, 3, 4, 5, 6]

In [12]:
len(x)

5

In [17]:
x=[1,2,3,4]
x.insert(2,'abc')
x

[1, 2, 'abc', 3, 4]

In [27]:
x

[1, 4]

In [30]:
x=[1,2,3,4,1,2,3,2]
x.count(2)

3

In [34]:
x=[1,2,3,4]
x.reverse()
x

[4, 3, 2, 1]

In [36]:
x.index(2)

2

In [37]:
a='abhi'
a[::-1]

'ihba'

In [38]:
x=[1,2,3,4]
y=['a','b','c','d']
list(zip(x,y))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [39]:
x=[1,2,3,4]
y=['a','b','c']
list(zip(x,y))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [48]:
x=[1,2,3,4]
y=['a','b','c','d']
z=['!','@','#']
a=list(zip(x,y,z))
a
type(a)

list

In [61]:
import numpy as np
z=np.random.randn(10)
z

array([ 0.5411408 , -0.16209585, -0.23703513,  0.90068294,  0.07221508,
       -0.51061621,  0.27770084, -1.08910727,  1.55950022, -1.95120696])

In [62]:
p=np.random.randn(5,5)
p*10

array([[ 14.43722103, -14.25489693,   7.14619196,  -4.26176443,
         13.91349768],
       [  8.45182136,  -0.10221739,  -8.78887781,   9.97698999,
         -3.94063097],
       [ 11.13489904, -20.45527138,  14.32345247,   8.44608171,
        -24.12647502],
       [  8.44549812, -15.78565953,  17.81599087,  -9.5745891 ,
        -19.56475481],
       [ -1.33039607, -15.89626226,  -8.19167516,  10.13746448,
         -5.6631983 ]])

In [64]:
x=np.random.randint(0,100,100)
x.shape

(100,)

In [68]:
x.reshape(4,25)

array([[71, 21, 62, 16, 66, 64, 36,  4, 22, 73, 79, 18, 59, 65, 19, 28,
        57, 81,  9, 63, 21, 83, 62, 18, 29],
       [ 9, 24, 25, 30, 95, 17, 68, 37,  5, 94, 45, 73, 97, 65, 30,  3,
        59, 51,  3, 22, 40, 97, 61, 35, 17],
       [52, 31, 99, 13, 91, 69, 76,  3, 79, 43, 21, 82, 17, 19,  0, 68,
        44, 47,  3,  4, 80,  1, 81, 56, 52],
       [46, 65, 82, 27, 24, 78, 83, 16, 83, 26, 60, 25, 51, 89, 44, 96,
        16, 57, 67, 41,  4, 91, 61, 76, 17]])

In [70]:
x=np.random.randint(20,60,(3,3))
x

array([[24, 30, 36],
       [29, 28, 43],
       [24, 35, 27]])

In [71]:
x[0]-x

array([[ 0,  0,  0],
       [-5,  2, -7],
       [ 0, -5,  9]])

In [74]:
p=pow((x[0]-x),2)

In [76]:
q=p.sum(axis=1)

In [77]:
np.sqrt(q)

array([ 0.        ,  8.83176087, 10.29563014])

In [79]:
cdb=np.random.randint(10,100,(1000,5))
cdb

array([[59, 10, 11, 15, 46],
       [69, 42, 76, 61, 98],
       [84, 60, 28, 64, 77],
       ...,
       [67, 95, 37, 45, 73],
       [44, 54, 85, 72, 66],
       [12, 71, 99, 97, 11]])

In [80]:
cdb[0]-cdb

array([[  0,   0,   0,   0,   0],
       [-10, -32, -65, -46, -52],
       [-25, -50, -17, -49, -31],
       ...,
       [ -8, -85, -26, -30, -27],
       [ 15, -44, -74, -57, -20],
       [ 47, -61, -88, -82,  35]])

In [83]:
d1=pow((cdb[0]-cdb),2)

In [85]:
d2=d1.sum(axis=1)

In [96]:
np.sqrt(d2)

array([  0.        , 100.84145973,  82.31646251,  89.01685234,
        41.55718951,  92.        , 106.32027088,  39.12799509,
        83.8987485 ,  90.97801932,  79.88116173, 109.45775441,
        91.88579869, 126.35268102, 115.92238783,  72.84915923,
        85.80209788,  47.63402146,  90.89554445,  92.42294088,
        63.92182726,  95.6765384 , 124.73572063,  87.03447593,
        94.22313941, 102.69858811,  89.24124607,  49.06118629,
       110.75197515, 103.22305944, 108.15729287, 119.43617542,
        97.93365101,  88.3119471 , 113.89029809,  45.68369512,
       108.8025735 ,  96.23928512,  87.34987121,  77.01298592,
       117.05554237, 105.0047618 ,  45.93473631,  87.33842224,
       108.00925886,  75.85512507,  95.96353474, 111.27443552,
        77.42738534,  99.40321926,  76.32823855, 107.91200119,
       101.10885223,  77.78817391, 138.97841559,  61.91930232,
        77.83957862,  86.33655078,  72.89718787,  71.10555534,
       105.89145386,  87.92041856,  90.66421565, 118.50

In [99]:
d2[1:].min()

547

In [101]:
d2[1:].argmin()

132

In [105]:
d2.index(547)

AttributeError: 'numpy.ndarray' object has no attribute 'index'