In [2]:
a=[1,2,3,4]
type(a)

list

In [3]:
a=[1,2,'abhi',3.56]
type(a)

list

In [11]:
a=['Data',['science','ML']]
a[1][1][0].lower()

'm'

In [6]:
a=[1,2,3]
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [7]:
a[1]/2

1.0

In [1]:
import numpy as np
a=[1,2,3,4]
b=np.array(a)
b/2

array([0.5, 1. , 1.5, 2. ])

In [3]:
x=[[1,2,3],[4,5,6],[7,8,9]]
y=np.array(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
y.sum(axis=0)

array([12, 15, 18])

In [5]:
y.sum(axis=1)

array([ 6, 15, 24])

In [24]:
y.sum()

45

In [6]:
y[0]
y[1]

array([4, 5, 6])

In [8]:
y[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
y[:,0]

array([1, 4, 7])

In [12]:
y[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
y[0:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [14]:
y.sum()

45

In [15]:
y.mean()

5.0

In [16]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
y[1].mean()

5.0

In [26]:
y[0:3,1:3].mean()

5.5

In [46]:
np.arange(20,40)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [48]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [52]:
np.random.randint(0,10)

8

In [53]:
np.random.randint(0,10,10)

array([4, 2, 5, 4, 1, 1, 8, 2, 9, 2])

In [60]:
np.random.randint(0,5,(2,4))

array([[3, 0, 3, 3],
       [2, 3, 3, 1]])

In [18]:
SDB=np.random.randint(35,100,(100,5))#marks from 35 to 100, 100 students, 5 subjects

In [19]:
SDB.shape# gives no of rows n columns

(100, 5)

In [21]:
SDB.max(),SDB.min(),SDB.mean()

(99, 35, 67.706)

In [25]:
SDB.mean(axis=0).min()

66.14