In [10]:
x=[1,2,3,4]
y=[7,8]
x.append(y)
x

[1, 2, 3, 4, [7, 8]]

In [14]:
c=[1,2,3,[5,6],[7,8]]
d=[10,11]
c.append(d)
c

[1, 2, 3, [5, 6], [7, 8], [10, 11]]

In [6]:
a=[1,2,3,4]
b=[5,6]
a.extend(b)
a

[1, 2, 3, 4, 5, 6]

In [12]:
len(x)

5

In [17]:
x=[1,2,3,4]
x.insert(2,'abc')
x

[1, 2, 'abc', 3, 4]

In [27]:
x

[1, 4]

In [30]:
x=[1,2,3,4,1,2,3,2]
x.count(2)

3

In [34]:
x=[1,2,3,4]
x.reverse()
x

[4, 3, 2, 1]

In [36]:
x.index(2)

2

In [37]:
a='abhi'
a[::-1]

'ihba'

In [38]:
x=[1,2,3,4]
y=['a','b','c','d']
list(zip(x,y))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]

In [39]:
x=[1,2,3,4]
y=['a','b','c']
list(zip(x,y))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [48]:
x=[1,2,3,4]
y=['a','b','c','d']
z=['!','@','#']
a=list(zip(x,y,z))
a
type(a)

list

In [3]:
import numpy as np
z=np.random.randn(10)
z

array([ 0.66801437, -0.46101666,  0.88892474,  0.62746073,  0.2887208 ,
       -1.14817728, -0.78953028, -0.7868479 , -0.16313059,  0.20024457])

In [4]:
p=np.random.randn(5,5)
p*10

array([[ 10.04052113, -16.22918265, -17.31053797,   7.814499  ,
          2.95005271],
       [ -0.85576947,  -1.00552721,  -9.62216457,  13.31856585,
          3.52549216],
       [  3.0330542 ,  -4.40733913,  15.64594405,  -2.1048984 ,
          9.19621318],
       [ -7.66266233, -10.99688294,  -8.98588532,  23.95339525,
        -12.77462956],
       [ -9.66648415,  -2.93811384,  -3.88962161,  -1.03621085,
         -2.1788941 ]])

In [5]:
x=np.random.randint(0,100,100)
x.shape

(100,)

In [6]:
x.reshape(4,25)

array([[11, 28, 64, 42, 90, 57, 63, 39, 15, 68, 28, 85, 26, 75, 33, 71,
        48, 70, 87, 69, 79, 30, 84, 73, 39],
       [95, 51, 12,  1, 94, 31, 62, 92,  9, 87, 33, 10, 12, 33, 68, 30,
        21,  8, 41, 56, 18, 43,  4, 71, 18],
       [52, 72, 37, 11, 19, 61,  9, 61, 26, 67, 93, 16, 67, 41, 41, 42,
        52, 75,  9, 95, 20,  6, 97, 25, 65],
       [51, 65, 60, 89, 77,  1,  9, 59, 56, 15, 26, 70, 39,  4, 15, 89,
        76,  1, 59,  4, 93, 83, 64,  4, 11]])

In [7]:
x=np.random.randint(20,60,(3,3))
x

array([[27, 39, 33],
       [44, 38, 25],
       [59, 31, 56]])

In [8]:
x[0]-x

array([[  0,   0,   0],
       [-17,   1,   8],
       [-32,   8, -23]])

In [9]:
p=pow((x[0]-x),2)

In [10]:
q=p.sum(axis=1)

In [11]:
np.sqrt(q)

array([ 0.        , 18.81488772, 40.21193853])

In [12]:
cdb=np.random.randint(10,100,(1000,5))
cdb

array([[83, 55, 28, 11, 70],
       [48, 40, 30, 77, 46],
       [12, 37, 53, 65, 46],
       ...,
       [12, 58, 79, 72, 53],
       [97, 37, 79, 63, 87],
       [27, 21, 56, 63, 75]])

In [13]:
cdb[0]-cdb

array([[  0,   0,   0,   0,   0],
       [ 35,  15,  -2, -66,  24],
       [ 71,  18, -25, -54,  24],
       ...,
       [ 71,  -3, -51, -61,  17],
       [-14,  18, -51, -52, -17],
       [ 56,  34, -28, -52,  -5]])

In [14]:
d1=pow((cdb[0]-cdb),2)

In [15]:
d2=d1.sum(axis=1)

In [16]:
np.sqrt(d2)

array([  0.        ,  79.9124521 ,  97.37556162,  66.92533153,
        64.7224845 ,  75.01333215,  26.81417536,  71.57513535,
        74.93997598,  76.81145748,  49.35585072,  91.56964563,
        85.67379996,  60.90155991,  60.76183012,  87.17224329,
        89.31965069,  68.33739825,  76.40026178,  87.46999486,
       112.68983983,  86.51589449,  90.68627239,  71.61703708,
        72.47068373, 110.09541317,  75.34586916,  92.66067127,
        46.5832588 ,  84.59314393,  66.9776082 ,  60.39039659,
        71.53320907,  57.36723804,  92.88164512,  77.68526244,
        49.96999099,  66.76076692,  84.13679338,  99.67948636,
        90.93954036,  83.24662155,  71.21095421,  92.59049627,
        91.45490692,  92.35799911, 105.95281969,  97.52435593,
       114.54256851,  86.45229899,  30.4466747 ,  98.62048469,
        74.41102069,  54.5802162 , 110.93691901,  77.6916984 ,
        70.85901495,  88.70738413,  74.61233142, 103.55674773,
        69.61321714,  74.66592262,  97.95407087,  98.68

In [17]:
d2[1:].min()

200

In [18]:
d2[1:].argmin()

148

In [ ]:
#Nearest neighbours Training DS and Testing DS

In [24]:
train=np.random.randint(10,100,(100,4))#Training data set

In [32]:
train[:,0]=np.random.randint(0,99,100)# making the col more realistic age

In [33]:
train[:,1]=np.random.randint(10000,100000,100)#making the col more realistic salary

In [34]:
train[:,2]=np.random.randint(1,20,100)#making the col more realistic Location

In [37]:
train[:,3]=np.random.randint(0,2,100)#making the col more realistic EMI or not

In [39]:
train.shape

(100, 4)

In [40]:
trainDS=train[0:80,:]

In [41]:
trainDS.shape

(80, 4)

In [57]:
testDS=train[80:100,:]

In [58]:
testDS.shape

(20, 4)

In [68]:
trainDS=trainDS[:,0:3]

In [69]:
trainDS.shape

(80, 3)

In [98]:
holdout=testDS[0,0:3]#Who comes newly to the system, not psrt of training DS

In [99]:
holdout.shape

(3,)

In [100]:
d=(holdout-trainDS)*(holdout-trainDS)

In [101]:
d1=d.sum(axis=1)

In [102]:
np.sqrt(d1)

D:\Python\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([32683.00956154, 44563.02263088, 39381.00839237,  2831.0778866 ,
       30627.00426095, 19382.01836755, 11270.03992894, 31872.01245607,
       35826.0144169 , 14502.02913388, 26611.0200293 , 14828.01402751,
       14620.05010251, 35546.00772239, 17786.01014843,    84.02975663,
        9811.07868687,  4856.09894874, 30379.00001646, 24253.00571063,
       24252.00199983, 10171.02364563, 28009.01329929, 25797.01434275,
       13266.05732688,  8033.0276982 , 41775.01244763,  1212.01072603,
       34816.00186696,  5576.02734929, 12761.02919047,  1516.43067761,
       36750.00462585,  7535.02422027, 30408.03041961, 46184.0057704 ,
       41159.01810053, 20081.00161845,  4311.11366122, 29037.01274236,
       36751.00746918, 17897.03087107,            nan, 10266.10252238,
       26458.04252019, 15186.00148163,  1645.54003294, 18581.01875571,
        7976.084315  ,  9494.01063829, 13632.00623533, 24533.04559161,
         178.54131175, 38691.02832699,  6107.05518233, 28378.01804214,
      

In [90]:
d1.argmin()

42

In [92]:
d1.min()

-1879341365

In [109]:
np.iinfo('int8') 

iinfo(min=-128, max=127, dtype=int8)

In [110]:
np.iinfo('int32') 

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [121]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [123]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [124]:
trainDS.shape[0]

80

In [126]:
x=[1,2,3]
x[0]=22
x

[22, 2, 3]

# Tuples

In [127]:
y=(1,2,3)
y[0]=22

TypeError: 'tuple' object does not support item assignment

In [128]:
y=(1,2,3,[1,2,3])
y[3][0]=22
y

(1, 2, 3, [22, 2, 3])

In [135]:
x={'k1':100,'k2':200,'k3':300}

In [136]:
x['k1']=50

In [137]:
x

{'k1': 50, 'k2': 200, 'k3': 300}

In [138]:
x.keys()

dict_keys(['k1', 'k2', 'k3'])

In [139]:
x.values()

dict_values([50, 200, 300])

x.items()

In [191]:
x={'k1':[1,2,'data science',4,5],'k2':['machine learning','data'],'k3':66}

In [192]:
a=x['k1'][2].split()

In [193]:
b=a[0].upper()

In [194]:
b

'DATA'

In [215]:
c=x['k2'][0].split()[0][::-1].upper()+str(d['k3'])

TypeError: string indices must be integers

In [211]:
c

'ENIHCAM'

TypeError: string indices must be integers