In [4]:
#P1- Printing hello world 

In [3]:
import numpy as np
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [2]:
txt='20'
x=txt.zfill(10)
print(x)

0000000020


In [4]:
np.random.randint(0,10,100)

array([9, 2, 9, 5, 2, 9, 2, 2, 5, 7, 3, 9, 9, 7, 3, 3, 2, 6, 1, 8, 8, 9,
       4, 0, 6, 6, 2, 7, 1, 4, 6, 2, 9, 9, 2, 6, 9, 3, 7, 7, 6, 1, 7, 7,
       1, 2, 1, 5, 9, 8, 2, 1, 3, 1, 4, 4, 2, 1, 8, 6, 7, 9, 0, 7, 5, 3,
       0, 0, 1, 5, 0, 6, 3, 0, 5, 1, 7, 7, 7, 3, 1, 9, 9, 2, 9, 1, 3, 7,
       9, 8, 8, 9, 9, 4, 4, 8, 0, 3, 2, 4])

In [11]:
np.random.randn(20)

array([-0.63164428, -1.42842056,  0.14645812,  0.47481981,  0.37935497,
       -0.89331549, -0.61250641, -0.90364648,  0.38369757,  0.18878483,
        0.34096502, -1.6102087 , -0.4329439 , -1.83258553,  0.53173825,
        0.1156742 , -0.82760156, -0.92943679, -0.52138362,  0.31061162])

In [12]:
np.random.randn(10)

array([-1.56971314,  0.31623628,  0.48473991,  0.43878467,  0.17875718,
        3.03229597, -0.21635086,  2.69150583,  0.488183  ,  0.10978291])

In [17]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [31]:
a=[1,2,3,4]
a[0]=100
a

[100, 2, 3, 4]

In [29]:
a=(1,2,3,4)
a[0]=3

TypeError: 'tuple' object does not support item assignment

In [9]:
import copy
a=[[1,2,3,4],['a','b','c','d']]
b=copy.deepcopy(a)
b

[[1, 2, 3, 4], ['a', 'b', 'c', 'd']]

In [10]:
b[0]=[2,3,4,5]
a

[[1, 2, 3, 4], ['a', 'b', 'c', 'd']]

In [11]:
b

[[2, 3, 4, 5], ['a', 'b', 'c', 'd']]

In [6]:
a=[[1,2,3,4],['a','b','c','d']]
b=copy.copy(a)
b

[[1, 2, 3, 4], ['a', 'b', 'c', 'd']]

In [7]:
b[0][0]=100
a

[[100, 2, 3, 4], ['a', 'b', 'c', 'd']]

In [8]:
b

[[100, 2, 3, 4], ['a', 'b', 'c', 'd']]

In [5]:
print('Hello World!') #Can directly assign a value

Hello World!


In [6]:
a='Hello World!' #Assign a value to variable and print the variable, both ways will work
print(a)

Hello World!


In [20]:
#P2- Add two numbers
num1=int(4.5)
num2=6
sum=num1+num2
print("Sum of {0} and {1} is {2}". format(num1,num2,sum))

Sum of 4 and 6 is 10


In [23]:
N1=input("Enter first num: ")
N2=input("Enter second num: ")
Sum=float(N1)+float(N2) #Here's a trick, the input returns a string, so we need to convert string to number first and then add he numbers
print("Sum of {0} and {1} is {2}". format(N1,N2,Sum))

Enter first num: 4.5
Enter second num: 3.2
Sum of 4.5 and 3.2 is 7.7


In [1]:
#Entire thing can be done in single line
print('The sum is %.1f' %(float(input("Enter first num: "))+float(input("Enter second num: ")))) #%.1f is as the input we are giving as float, so formatting as to done.

Enter first num: 1
Enter second num: 2
The sum is 3.0


In [47]:
#P3- Finding square for positive number
num=5
num_sqrt=num**0.5
print('The square root of %.3f is %.3f'%(num,num_sqrt))

##For complex number and negative numbers, we use cmath module
import cmath
num=1+2j
num_sqrt=cmath.sqrt(num)
print('The squre root of {0} is {1:.3f}+{2:.3f}j'.format(num,num_sqrt.real,num_sqrt.imag))
#To take input from the user, then use EVAL to convert complex numbers as well.
import math
import numpy as np
num=[1,2,3]
print(np.sqrt(num))
num=10
print(math.sqrt(num))
#The math works for single number and numpy workd for list,tuple not for set.

The square root of 5.000 is 2.236
The squre root of (1+2j) is 1.272+0.786j
[1.         1.41421356 1.73205081]
3.1622776601683795


In [54]:
#P4- Calculate area of triangle
#Area of triangle is given by (1/2)*(base*height) or semi perimeter is given by s=(a+b+c)/2 and area is (s*(s-a)*(s-b)*(s-c))**0.5
a=5
b=10
c=7
s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
print('The area of triangle is %.2f' %area)

The area of triangle is 16.25


In [60]:
#P5- Quadratic equation
#Solve the quadratic equation a*x**2+b*x+c=0
a=1
b=5
c=6
#Find the discriminent
#d=bsquare-4ac
d=(b**2)-(4*a*c)
#Find two solutions
sol1=(-b-cmath.sqrt(d))/(2*a)
sol2=(-b+cmath.sqrt(d))/(2*a)

print(" The two solutions are {0} and {1}".format(sol1,sol2))


 The two solutions are (-3+0j) and (-2+0j) :)


In [74]:
#P6- Swapping two number using temporary variable
x=4
y=5

temp=x
x=y
y=temp

print("The value of x after swapping is {}" .format(x))
print("The value of y after swapping is {}" .format(y))
print('**************************************************')
#Another method is direct one
x=1
y=2
x,y=y,x
print("The value of x after swapping is {}" .format(x))
print("The value of y after swapping is {}" .format(y))

The value of x after swapping is 5
The value of y after swapping is 4
**************************************************
The value of x after swapping is 2
The value of y after swapping is 1


In [81]:
#P6- # Program to generate a random number between 0 and 9
import random
print(random.randint(0,9))
import numpy as np
print(np.random.randint(0,9,10))#low,high,size
print(np.random.randn(5,5))

1
[7 0 8 5 3 4 1 6 7 2]
[[ 0.22857332  0.48843953  0.27491146  0.2236774  -0.17404635]
 [-0.1103269   0.90614372 -0.18557588 -0.19313296 -0.22588615]
 [ 0.49316546  0.32798446 -0.21091749  0.42088812  1.14271374]
 [ 0.27067967  1.08933349  0.04359735 -0.94784203  0.30053295]
 [ 0.25876792  0.27750402 -0.44944467 -0.20102129 -0.46358901]]


In [89]:
#P-7 Kilometers to miles
#For this u need a conv_factor=0.621
kilometers=3.5
conv_factor=0.621
miles=kilometers*conv_factor
print('The %.2f Kilometers is equal to %.2f miles' %(kilometers,miles))

The 3.50 Kilometers is equal to 2.17 miles


In [90]:
#P8- Celsius to fahrenheit
celsius=35
fahrenheit=(celsius*1.8)+32
print('The fahrenheit is ',format(fahrenheit))

The fahrenheit is  95.0


In [102]:
#P9- To check number is Positive, Negative or Zero.
#This can be done in two ways, one way is using if,elif and other one is using Nested if.
num=float(input('Enter a number'))
if num>0:
    print('Positive Number')
elif num==0:
    print('Zero')
else:
    print('Negative Number')
print('***********************')

num=int(input('Enter a number'))
if num>=0: #Should give num>=0 first for nested if
    if num==0:
        print('Zero')
    else:
        print('Positive number')
else:
    print('Negative number')

Enter a number0
Zero
***********************
Enter a number0
Zero


In [111]:
#P10- Check if a number is odd or even
num=input('Enter a number') #Always the input returns string, so we need use int or float.
if (num % 2) == 0:
    print('Even')
else:
    print('Odd')

Enter a number3


TypeError: not all arguments converted during string formatting

In [ ]:
#P11- To check is the given year is leap or not.
#We say year is leap if it exactly divides by 4 and for century year it as to divide by 400, remainder should be Zero.
year=int(input('Enter a year :'))
if (year%4)==0:
    if (year%100)==0:
        if (year%400)==0:
            print('Leap year')
        else:
            print('Not a Leap year')
    else:
        print('Leap year')
else:
    print('Not a leap year')

In [1]:
#P12- Finding the largest number
num1=10
num2=15
num3=20
if (num1>=num2) and (num1>=num3):
    largest=num1
elif (num2>=num1) and (num2>=num3):
    largest=num2
else:
    largest=num3
print('The largest number is :',largest)

The largest number is : 20


In [6]:
#P13- Given number is prime number or not, the number is said to be prime if its factor is 1.
num=4
if num>1: #Prime numbers are always greater than one.
    for i in range(2,num):
        if num%i==0:
            print(num," is not a prime number")
            print(i,"times",num//i,"is",num)
            break
        else:
            print(num,"is a prime number")
else: #For num less than one.
    print(num,"is not a prime number")


4  is not a prime number
2 times 2 is 4


In [17]:
#P14-Print all the prime numbers within an interval
lower=900
upper=1000
print("Prime numbers between", lower, "and", upper, "are:")
for num in range(lower,upper+1):
    if num>1: #All prime numbers are greater than 1.
        for i in range(2,num):
            if (num%i)==0:
                break
        else:
            print(num)

Prime numbers between 900 and 1000 are:
907
911
919
929
937
941
947
953
967
971
977
983
991
997


In [18]:
#P15-Finding factorial of a number.
num=7
factorial=1
if num<0:
    print("Factorial doesn't exist for negative number")
elif num==0:
    print('The Factorial is 1')
else:
    for i in range(1,num+1):
        factorial=factorial*i
    print('The factorial of',num,'is',factorial )

1
2
3
4
5
6


In [19]:
#P16-Fibbonicci series
def fib(a,b):
    while(a<10):
        print(a)
        a,b=b,a+b

fib(0,1)

0
1
1
2
3
5
8


In [ ]:
#palindrome, perfect squares, sub list

In [18]:
#Creating a sublists
seq=[1,2,3,4,5,6,7,8,9,10]
[seq[i:i+2] for i in range(0,len(seq),3)]

[[1, 2], [4, 5], [7, 8], [10]]

In [26]:
#Palindrome

In [11]:
#Size of the string
n=int(input())
#Give the list of numbers having size n
l=list(map(int,input().split(' '))) #We must use split
print(l)
print('The plindrome number are:')
#Go through the list to check if the given number is palindrome or not
for i in l:
    num=str(i)
    if (num==num[::-1]):
        print(i)

3
123
[123]
The plindrome number are:


In [4]:
def is_palindrome(n):
    return str(n)==str(n)[::-1]

n=str(input('Enter the value:'))
if is_palindrome(n):
    print('The number {0} is palindrome:'.format(n))
else:
    n1=n
    while not is_palindrome(n1):
        n1=int(n1)-1
    print('The next palindrome is {1}'.format(n,n1))
        

Enter the value:123
The next palindrome is 121


In [1]:
import math
def is_square(integer):
    root=math.sqrt(integer)
    return integer==int(root)**2

integer=int(input('Enter a integer'))
if is_square(integer):
    print('The given integer {0} is a perfect square'.format(integer))
else:
    print('Not a perfect square')



Enter a integer3
Not a perfect square


In [34]:
seq=[1,2,3,4,5,6,7,8,9,10]
[seq[i:i+3] for i in range(0,len(seq),3)]

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]

In [3]:
l=[1,2,3,4,5]
a=[i**2 for i in l]
print(a)

[1, 4, 9, 16, 25]


In [110]:
l=['cat','dog','cat','dog','sheep','sheep','sheep']
from collections import Counter
c=Counter(l)
print(c.items())

dict_items([('cat', 2), ('dog', 2), ('sheep', 3)])


In [67]:
#l=['cat','dog','cat','dog','sheep','sheep','sheep']
from collections import defaultdict
l = ['a', 'a', 'b', 'b', 'b']
d = defaultdict(int)
for i in l:
    print(i)
    d[i] += 1
d

a
a
b
b
b


defaultdict(int, {'a': 2, 'b': 3})

In [5]:
num=5##FInding prime or not
for i in range(2,num):
    if num%i==0:
        print('Not prime')
else:
    print('prime')

prime


In [ ]:
#Finding second largest number

In [62]:
l = ['a', 'b', 'a', 'b', 'b']
d={}
for i in l:
    if i in d:d[i]+=1
    else: d[i]=1

In [63]:
mytups = [(i, d[i]) for i in d]
mytups

[('a', 2), ('b', 3)]

In [71]:
l=[1,2,3,4,5,6,7]
l.sort()
print('The second largest value in a list',l[-2])

The second largest value in a list 6


In [74]:
max([n for n in l if n!=max(l)])

6

In [86]:
alist=[10, 0,3,10,90,5,-2,4,18,45,707, 100,1,-266,706, 1]
largest = alist[0]
second_largest = alist[0]
for i in range(len(alist)):
    if alist[i] > second_largest:
        second_largest = alist[i]
    if alist[i] > largest:
        tmp = second_largest
        second_largest = largest
        largest = tmp

print(largest, second_largest)

707 706


In [77]:
l=[1,2,3,4,5]
l[0]

1

In [87]:
l=[1,2,3,4,5] #iterable
for i in l: #i is the iterator, which traverse through the list of values.
    print(i)

1
2
3
4
5


In [19]:
l=[1,2,3,4,5]
list=iter(l)

In [21]:
print(next(list))

2


In [23]:
import random
for i in random.randint(1,2):# we cannot iterate the integer
    print(i)

TypeError: 'int' object is not iterable

In [7]:
i=3
for j in i:
    print(j)

TypeError: 'int' object is not iterable

In [26]:
i='Love the nature'
l=i.split()
for i in l:
    i.split()
    print(i)

Love
the
nature


In [33]:
a=lambda x:x*x
print('The square of 4 is:',a(4))

The square of 4 is: 16


In [35]:
l1=set(map(lambda n:n**2,[1,2,3,4])) #Any number of arguments can be passed, but should have only one expression.
print(l1)

{16, 1, 4, 9}


In [36]:
l1=[1,2,3,4,5]
l2=[4,5,6,7]
l3=set(map(lambda x,y:x+y,l1,l2))
print(l3)

{9, 11, 5, 7}


In [37]:
l1=range(10)
l1

range(0, 10)

In [38]:
l2=range(10,20)
l2

range(10, 20)

In [39]:
l3=set(map(lambda x,y:x+y,l1,l2))
l3

{10, 12, 14, 16, 18, 20, 22, 24, 26, 28}

In [41]:
l4=set(filter(lambda x:x>15,l3))
l4

{16, 18, 20, 22, 24, 26, 28}

In [67]:
from functools import reduce
reduce(lambda x,y:x*y, l4)

2214051840

In [68]:
reduce(lambda x,y:x*y,filter(lambda x:x>15,map(lambda x,y:x+y,l1,l2)))

2214051840

In [74]:
for i in range(10,20):
    print(i)

10
11
12
13
14
15
16
17
18
19


In [3]:
cas0=10
print(cas0)

10


In [4]:
cash=10
print(cash)

10


In [5]:
123cash=10

SyntaxError: invalid syntax (<ipython-input-5-c5349cbac094>, line 1)

In [6]:
cash123=10

In [8]:
_abc=10
print(_abc)

10


In [9]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [10]:
a=10
type(a)

int

In [11]:
a=1+2j

In [12]:
x=10
y=10
y is x

True

In [13]:
x==y

True

In [93]:
x=257
y=257
x is y

False

In [14]:
x=10
y=20
x==y

False

In [94]:
x=10.1 #Reusing is not there for floating and complex datatype
y=10.1
x is y

False

In [17]:
x=10+2j
Y=10+2j
x is y

False

In [27]:
x=10+2j
y=10+2j
id(x),id(y)

(2051096300464, 2051096300208)

In [30]:
a='abhi'
b='abhi'
a is b
id(a),id(b)

(2051096468200, 2051096468200)

In [29]:
a=True
b=True
a is b
id(a),id(b)

(140728445016400, 140728445016400)

In [26]:
a='abhi'
b='abhi'
a is b
##id(a)
id(a),id(b)

(2051096273896, 2051096273896)

In [25]:
a=5
b=5
id(a),id(b)

(140728445539264, 140728445539264)

In [35]:
l=[1,2,3]
l.append([1,2,3,4])
l

[1, 2, 3, [1, 2, 3, 4]]

In [32]:
l.append('Null')
l

[1, 2, 3, 10, 'Null']

In [33]:
l[0]=l[0]/2
l

[0.5, 2, 3, 10, 'Null']

In [34]:
s=(10,20,10)
s=s/2

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

In [127]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [130]:
s={1,2,3,4,'abc'}
s[0]=

TypeError: 'set' object does not support item assignment

In [36]:
d={1:'abhi',2:'abc'}
d

{1: 'abhi', 2: 'abc'}

In [37]:
d[1]='abhishek'
d

{1: 'abhishek', 2: 'abc'}

In [133]:
10<20

True

In [136]:
10<20<15

False

In [137]:
10 and 20

20

In [138]:
4&5

4

In [139]:
4|5

5

In [140]:
4^5

1

In [141]:
~4

-5

In [174]:
a=10
bin_a=bin(a)
ones_1=[]
for i in bin_a:
    if i not in ('b','0'):
      ones_1.append(i)  
print(len(ones_1))

2


In [177]:
s='Abhi is a good boy'
'g' in s

True

In [4]:
a,b=[int(x)for x in input('Enter 2 numbers: ').split(',')]
print('Teh value of a',a)##,print('Teh value of b',b)

Enter 2 numbers: 2,4
Teh value of a 2


In [3]:
s='Abhishek'
count=0
for x in s:
    count=count+1
print('The total no characters',count)

The total no characters 8


In [4]:
s='Abhishek'
i=0
for x in s:
    print('The value at index position i is',x)
    i=i+1

The value at index position i is A
The value at index position i is b
The value at index position i is h
The value at index position i is i
The value at index position i is s
The value at index position i is h
The value at index position i is e
The value at index position i is k


In [9]:
n=10
sum=0
i=1
while i<=n:
    sum=sum+i
    i+=1
print(sum)

55


In [33]:
name=''
while name!='Abhi':
    name=input('Enter the name ')
print('Hello')

Enter the name ahi
Enter the name Abhi
Hello


In [32]:
name=''
pwd=''
while (name!='Abhi') or (pwd!='xyz'):
    name=input('name')
    pwd=input('pwd')
print('Hello')

namexyz
pwdabh
nameabhi
pwdxyz
nameAbhi
pwdxyz
Hello


In [11]:
n=4
for i in range(1+n+1):
    print('*'*i)


*
**
***
****
*****


In [8]:
n=int(input('Enter a number'))
for i in range(1,n+1):
    for j in range(i):
        print(j)
        print('*',end='')
    print()

Enter a number3
0
*
0
*1
*
0
*1
*2
*


In [24]:
n=int(input('Enter a number :'))
for i in range(n): #Specifies row number
    for j in range(n): # specifies column
        print('*',end=' ')
    print()

Enter a number :2
* * 
* * 


In [19]:
range(1)

range(0, 1)

In [32]:
def holidaybush(n):
    z=n-1
    x=1
    for i in range(0,n):
        for i in range(0,z):
            print(' ',end='')
        for i in range(0,x):
            print('*',end='')
        for i in range(0,z):
            print(' ',end='')
        x=x+2
        z=z-1
        print()
holidaybush(20)

                   *                   
                  ***                  
                 *****                 
                *******                
               *********               
              ***********              
             *************             
            ***************            
           *****************           
          *******************          
         *********************         
        ***********************        
       *************************       
      ***************************      
     *****************************     
    *******************************    
   *********************************   
  ***********************************  
 ************************************* 
***************************************


In [39]:
j=int(input('Enter a number'))
for i in range(1,j+1,2):
    print(' '*j+i*'*')
    j=j-1

Enter a number5
     *
    ***
   *****


In [10]:
s=input('Enter a string:')
sub=input('Enter substring:')
flag=False
pos=-1
n=len(s)
count=0
while True:
    pos=s.rfind(sub,pos+1,n)
    if pos==-1:
        break
    print('Found at index:',pos)
    flag=True
    count=count+1
if flag==False:
    print('Not found')
print('NUmber of occurances is:',count)

Enter a string:herighdlng\
Enter substring:h
Found at index: 5
NUmber of occurances is: 1


In [11]:
s='ababab'
s=s.replace('a','b')
print(s)

bbbbbb


In [14]:
s='Abhi Is A Good Boy'
print(s.title())

Abhi Is A Good Boy


In [15]:
a='Abhi is a boy'
a[::-1]

'yob a si ihbA'

In [53]:
s=input('Enter a string: ')
words=[]
s1=s.split()
for word in s1:
    words.append(word)
print(tuple(reversed(words)))

Enter a string: abhi shek
('shek', 'abhi')


In [8]:
s=input('Enter a string: ')
alpha=''
num=''
output=''
for i in s:
    if i.isalpha():
        alpha=alpha+i #We cannot append the list like .append, so we need to add the string. If we are adding output value to output then convert to str and then add.
    else: 
        num=num+i
print(alpha)
print(num)

for x in sorted(alpha):
    output=output+x
for x in sorted(num):
    output=output+x
print(output)

Enter a string: AD65CB53
ADCB
6553
ABCD3556


In [55]:
s = input("Enter a string: ")
output = ''
for i in range(len(s) - 1):
    if s[i].isalpha() and s[i+1].isdigit():
        output += s[i] * int(s[i+1])
print(output)

Enter a string: a2v2
aavv


In [62]:
s=input('Enter a string : ')
output=''
for i in range(len(s)):
    if s[i].isalpha() and s[i+1].isdigit():
        output=output+s[i]*int(s[i+1])
print(output)

Enter a string : a2v2
aavv


In [12]:
s={10,20,30}
s[0]

TypeError: 'set' object is not subscriptable

In [14]:

print(s[0])

TypeError: 'set' object is not subscriptable

In [3]:
w=input('Enter a word:')
s=set(w)
v={'a','e','i','o','u'}
d=v.intersection(s)
print('The vowels are:',d)
print('The number of vowels are:',len(d))

Enter a word:abhi is a good boy
The vowels are: {'a', 'o', 'i'}
The number of vowels are: 3


In [81]:
rec={}
n=int(input('Enter number of students:'))
i=1
while i<=n:
    name=input('Enter a name')
    marks=input('Enter % of marks')
    rec[name]=marks
    i=i+1
print('Name of student','\t','% of marks')
for x in rec:
    print('\t',x,'\t\t',rec[x])

Enter number of students:1
Enter a nameabhi
Enter % of marks12
Name of student 	 % of marks
	 abhi 		 12


In [9]:
d=dict([('1','abhi')])
print(d)

{'1': 'abhi'}


In [12]:
s={1,2,3}
s.add('Abhi',range(1,5))
print(s)

TypeError: add() takes exactly one argument (2 given)

In [15]:
s={1,2,3}
s.update('Abhi',range(1,5),[10,11,12])
print(s)

{1, 2, 3, 'h', 4, 10, 11, 12, 'i', 'b', 'A'}


In [65]:
d={'A':1000,'B':1000,'C':1000}
s=sum(d.values())
print(s)

3000


In [66]:
word=input('Enter a word :')
d={}
for x in word:
    print(x)
    d[x]=d.get(x,0)+1
for k,v in sorted(d.items()): #sorted to get in alphabetical order.
    print(k,'occured',v,'times')

Enter a word :abhishek
a
b
h
i
s
h
e
k
a occured 1 times
b occured 1 times
e occured 1 times
h occured 2 times
i occured 1 times
k occured 1 times
s occured 1 times


In [ ]:
n=int(input('Enter no of students :'))
d={}
for x in range(n):
    name=input('Enter a name')
    marks=input('Enter a marks')
    d[name]=marks
while True:
    name=input('Enter the student name to get the marks')
    marks=d.get(name,-1) #get is the function that returns corresponding value of the key.
    if marks==-1:
        print('Student not found')        
    else:
        print('The marks of {}:{}'.format(name,marks))
    option=input('Do u want to find another student marks[Yes|No]: ')
    if option=='No':
        break
print('Thanks for using out application')

Enter no of students :2
Enter a nameabhi
Enter a marks20
Enter a nameabhi
Enter a marks30
Enter the student name to get the marksabhi
The marks of abhi:30


In [29]:
def calc(a,b):
    sum=a+b
    mul=a*b
    sub=a-b
    return sum,mul,sub

In [34]:
sum,mul,sub=calc(1,2)
sum,mul,sub

(3, 2, -1)

In [36]:
def factorial(n):
    if n==0:
        result=1
    else:
        result=n*factorial(n-1)
    return result
factorial(3)

6

In [37]:
s=lambda n:n*n
print(s(4))

16


In [38]:
xx=50
def var_test():
    xx=100
    return xx
print(var_test())

100


In [40]:
import module1

ModuleNotFoundError: No module named 'module1'

In [2]:
from random import *
for i in range(10):
    print(random()) ###Between 0 and 1

0.9302696669260591
0.35101544298854503
0.2261792569248694
0.3187158448785401
0.12484074832641479
0.9754370458331754
0.4472379450626611
0.8984616491098434
0.4652112807036881
0.46766568564482736


In [4]:
for i in range(5):
    print(uniform(1,10))

5.5807319379577045
1.2881976007044784
8.989619862007967
5.981194853144253
9.571177541374823


In [5]:
list=['A','B','C','D']
for i in range(5):
    print(choice(list))

B
D
B
A
D


In [7]:
for i in range(10):
    print(randint(100000,999999))

955052
478062
243415
822651
612342
485938
207584
521846
786874
515457


In [64]:
chr(65)

'A'

In [28]:
# import library 
import math, random 
  
# function to generate OTP 
def generateOTP() : 
  
    # Declare a digits variable   
    # which stores all digits  
    digits = "0123456789"
    OTP = "" 
  
   # length of password can be chaged 
   # by changing value in range 
    for i in range(6) : 
        OTP += digits[math.floor(random.random() * 10)] 
  
    return OTP 
  
# Driver code 
if __name__ == "__main__" : 
      
    print("OTP of 4 digits:", generateOTP())

OTP of 4 digits: 211092


In [18]:
digits = "0123456789"
otp = "" 
for i in range(6):
    otp=otp+digits[math.floor(random.random()*10)]
print(otp)

954837


In [30]:
try:
    print('try')
    #print(10/0)
except:
    print('except')
else:
    print('else')
finally:
    print('finally')

try
else
finally


In [31]:
try:
    print('enter the value')
except:
    print('Enter correct value')
finally:
    print('entered')

enter the value
entered


In [24]:
from sys import argv
args=argv[1:]
sum=0
for x in args:
    n=int(n)
    sum+=n
print("The sum is:",sum)
#Give values in command line.

The sum is: 10


In [22]:
from sys import argv
print(type(argv))

<class 'list'>


In [29]:
print(argv[3:50])

[]
